apiVersion: v1 # if in the core group, no need to add the group name
kind: Pod # kind of Kubernetes object
metadata: 
  name: pipeline-pod
  namespace: ben-space
  labels:
    app: pipeline-demo
spec:
  # restartPolicy: Never
  containers:
  - name: hello
    image: barayathel/pipeline-example 
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 8080 #has to match ports from the application

